# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    dir: ./cmd/traefik-domain
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
    goarm:
      - '7'
    gomips:
      - hardfloat
      - softfloat
    ignore:
      # freebsd: only amd64
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: mips
      - goos: freebsd
        goarch: mipsle
      - goos: freebsd
        goarch: mips64
      - goos: freebsd
        goarch: mips64le
      # windows/darwin: no mips
      - goos: windows
        goarch: mips
      - goos: windows
        goarch: mipsle
      - goos: windows
        goarch: mips64
      - goos: windows
        goarch: mips64le
      - goos: darwin
        goarch: mips
      - goos: darwin
        goarch: mipsle
      - goos: darwin
        goarch: mips64
      - goos: darwin
        goarch: mips64le

    ldflags:
      - -s -w -X main.version={{.Tag}} -X main.buildTime={{.Date}}
archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest"
      - "{{ .Env.DOCKER_USERNAME }}/traefik-domain:{{ .Tag }}"
      - "{{ .Env.DOCKER_USERNAME }}/traefik-domain:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64,linux/arm/v7"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
